### ISSUE TITLE
Default dse settings not compatible with 4.8.x

### ISSUE THREAD

**Issue by larsp** [target/dse-cookbook#45]
The latest dse.yaml default settings will result in errors during cassandra startup when the cassandra version is 4.8.x. The default version (currently 4.7.2-1) works though.

```
tail: /var/log/cassandra/output.log: file truncated
INFO  10:26:34  Loading DSE module
INFO  10:26:34  Loading settings from file:/etc/dse/dse.yaml
Exception in thread "main" java.lang.ExceptionInInitializerError
	at com.datastax.bdp.DseCoreModule.<init>(DseCoreModule.java:39)
	at com.datastax.bdp.DseModule.getRequiredModules(DseModule.java:98)
	at com.datastax.bdp.server.AbstractDseModule.configure(AbstractDseModule.java:26)
	at com.datastax.bdp.DseModule.configure(DseModule.java:35)
	at com.google.inject.AbstractModule.configure(AbstractModule.java:59)
	at com.google.inject.spi.Elements$RecordingBinder.install(Elements.java:223)
	at com.google.inject.spi.Elements.getElements(Elements.java:101)
	at com.google.inject.internal.InjectorShell$Builder.build(InjectorShell.java:133)
	at com.google.inject.internal.InternalInjectorCreator.build(InternalInjectorCreator.java:103)
	at com.google.inject.Guice.createInjector(Guice.java:95)
	at com.google.inject.Guice.createInjector(Guice.java:72)
	at com.google.inject.Guice.createInjector(Guice.java:62)
	at com.datastax.bdp.DseModule.main(DseModule.java:71)
Caused by: org.yaml.snakeyaml.error.YAMLException: Unable to find property 'enabled' on class: com.datastax.bdp.config.NodeHealthOptions
	at org.yaml.snakeyaml.introspector.PropertyUtils.getProperty(PropertyUtils.java:132)
	at org.yaml.snakeyaml.introspector.PropertyUtils.getProperty(PropertyUtils.java:121)
	at org.yaml.snakeyaml.constructor.Constructor$ConstructMapping.getProperty(Constructor.java:308)
	at org.yaml.snakeyaml.constructor.Constructor$ConstructMapping.constructJavaBean2ndStep(Constructor.java:240)
	at org.yaml.snakeyaml.constructor.Constructor$ConstructMapping.construct(Constructor.java:189)
	at org.yaml.snakeyaml.constructor.BaseConstructor.constructObject(BaseConstructor.java:182)
	at org.yaml.snakeyaml.constructor.Constructor$ConstructMapping.constructJavaBean2ndStep(Constructor.java:296)
	at org.yaml.snakeyaml.constructor.Constructor$ConstructMapping.construct(Constructor.java:189)
	at org.yaml.snakeyaml.constructor.Constructor$ConstructYamlObject.construct(Constructor.java:331)
	at org.yaml.snakeyaml.constructor.BaseConstructor.constructObject(BaseConstructor.java:182)
	at org.yaml.snakeyaml.constructor.BaseConstructor.constructDocument(BaseConstructor.java:141)
	at org.yaml.snakeyaml.constructor.BaseConstructor.getSingleData(BaseConstructor.java:127)
	at org.yaml.snakeyaml.Yaml.loadFromReader(Yaml.java:481)
	at org.yaml.snakeyaml.Yaml.load(Yaml.java:412)
	at com.datastax.bdp.config.DseConfigYamlLoader.<clinit>(DseConfigYamlLoader.java:58)
```

**Comment by mdbelt** [comment]
Yes, it looks like Datastax removed the enabled attribute from the "node_health_options" section between 4.7.* & 4.8.*.  I checked & the documentation agrees.
https://docs.datastax.com/en/datastax_enterprise/4.7/datastax_enterprise/config/configDseYaml.html
vs...
https://docs.datastax.com/en/datastax_enterprise/4.8/datastax_enterprise/config/configDseYaml.html

I'll remove this attribute since I introduced it with PR#44.

**Comment by dcparker88** [comment]
@larsp did this fix your issue? It seems to be starting ok for me.

**Comment by larsp** [comment]
looks like it, thanks @dcparker88

**Comment by dcparker88** [comment]
cool, I will close this for now
